name: one_trick_pony
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0


dependencies:
  flutter:
    sdk: flutter

  
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true
  fonts:
    - family: jost
      fonts:
        - asset: assets/Jost/Jost-wghtfree.ttf
          weight: 600
    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/onetrickpony.png"
